In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt # for data visualization
import seaborn as sns # for statistical data visualization
import socket
import struct

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [5]:
data = 'C:\\Users\\udayk\\Desktop\\mmj\\mmj\\sample4.csv'
df = pd.read_csv(data)

In [6]:
df.shape

(59999, 78)

In [7]:
df.columns[df.isnull().any()]

Index([], dtype='object')

In [8]:
df.columns[df.isnull().any()].tolist()

[]

In [9]:
df.head()

,Dst_Port,Protocol,Flow_Duration,Tot_Fwd_Pkts,Tot_Bwd_Pkts,TotLen_Fwd_Pkts,TotLen_Bwd_Pkts,Fwd_Pktl_Len_Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,target_class
0,80,6,3974862,29,44,86,59811,86,0,2.965517,...,0,0.0,0.0,0,0,0.0,0.0,0,0,0
1,80,6,63,1,1,0,0,0,0,0.000000,...,0,0.0,0.0,0,0,0.0,0.0,0,0,0
2,80,6,476078,2,6,86,3037,86,0,43.000000,...,0,0.0,0.0,0,0,0.0,0.0,0,0,0
3,80,6,151,2,1,0,0,0,0,0.000000,...,0,0.0,0.0,0,0,0.0,0.0,0,0,0
4,80,6,472507,2,5,73,1050,73,0,36.500000,...,0,0.0,0.0,0,0,0.0,0.0,0,0,0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59999 entries, 0 to 59998
Data columns (total 78 columns):
Dst_Port             59999 non-null int64
Protocol             59999 non-null int64
Flow_Duration        59999 non-null int64
Tot_Fwd_Pkts         59999 non-null int64
Tot_Bwd_Pkts         59999 non-null int64
TotLen_Fwd_Pkts      59999 non-null int64
TotLen_Bwd_Pkts      59999 non-null int64
Fwd_Pktl_Len_Max     59999 non-null int64
Fwd Pkt Len Min      59999 non-null int64
Fwd Pkt Len Mean     59999 non-null float64
Fwd Pkt Len Std      59999 non-null float64
Bwd Pkt Len Max      59999 non-null int64
Bwd Pkt Len Min      59999 non-null int64
Bwd Pkt Len Mean     59999 non-null float64
Bwd Pkt Len Std      59999 non-null float64
Flow Pkts/s          59999 non-null float64
Flow IAT Mean        59999 non-null float64
Flow IAT Std         59999 non-null float64
Flow IAT Max         59999 non-null int64
Flow IAT Min         59999 non-null int64
Fwd IAT Tot          59999 non-null int64
Fwd IAT Mean         59999 non-null float64
Fwd IAT Std          59999 non-null float64
Fwd IAT Max          59999 non-null int64
Fwd IAT Min          59999 non-null int64
Bwd IAT Tot          59999 non-null int64
Bwd IAT Mean         59999 non-null float64
Bwd IAT Std          59999 non-null float64
Bwd IAT Max          59999 non-null int64
Bwd IAT Min          59999 non-null int64
Fwd PSH Flags        59999 non-null int64
Bwd PSH Flags        59999 non-null int64
Fwd URG Flags        59999 non-null int64
Bwd URG Flags        59999 non-null int64
Fwd Header Len       59999 non-null int64
Bwd Header Len       59999 non-null int64
Fwd Pkts/s           59999 non-null float64
Bwd Pkts/s           59999 non-null float64
Pkt Len Min          59999 non-null int64
Pkt Len Max          59999 non-null int64
Pkt Len Mean         59999 non-null float64
Pkt Len Std          59999 non-null float64
Pkt Len Var          59999 non-null float64
FIN Flag Cnt         59999 non-null int64
SYN Flag Cnt         59999 non-null int64
RST Flag Cnt         59999 non-null int64
PSH Flag Cnt         59999 non-null int64
ACK Flag Cnt         59999 non-null int64
URG Flag Cnt         59999 non-null int64
CWE Flag Count       59999 non-null int64
ECE Flag Cnt         59999 non-null int64
Down/Up Ratio        59999 non-null int64
Pkt Size Avg         59999 non-null float64
Fwd Seg Size Avg     59999 non-null float64
Bwd Seg Size Avg     59999 non-null float64
Fwd Byts/b Avg       59999 non-null int64
Fwd Pkts/b Avg       59999 non-null int64
Fwd Blk Rate Avg     59999 non-null int64
Bwd Byts/b Avg       59999 non-null int64
Bwd Pkts/b Avg       59999 non-null int64
Bwd Blk Rate Avg     59999 non-null int64
Subflow Fwd Pkts     59999 non-null int64
Subflow Fwd Byts     59999 non-null int64
Subflow Bwd Pkts     59999 non-null int64
Subflow Bwd Byts     59999 non-null int64
Init Fwd Win Byts    59999 non-null int64
Init Bwd Win Byts    59999 non-null int64
Fwd Act Data Pkts    59999 non-null int64
Fwd Seg Size Min     59999 non-null int64
Active Mean          59999 non-null float64
Active Std           59999 non-null float64
Active Max           59999 non-null int64
Active Min           59999 non-null int64
Idle Mean            59999 non-null float64
Idle Std             59999 non-null float64
Idle Max             59999 non-null int64
Idle Min             59999 non-null int64
target_class         59999 non-null int64
dtypes: float64(23), int64(55)
memory usage: 35.7 MB

In [11]:
df['target_class'].value_counts()

0    30000
1    29999
Name: target_class, dtype: int64

In [12]:
X = df.drop(['target_class'], axis=1)

y = df['target_class']

In [13]:
# split X and y into training and testing sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [14]:
# check the shape of X_train and X_test

X_train.shape, X_test.shape

((47999, 77), (12000, 77))

In [15]:
np.isnan(X_train)

,Dst_Port,Protocol,Flow_Duration,Tot_Fwd_Pkts,Tot_Bwd_Pkts,TotLen_Fwd_Pkts,TotLen_Bwd_Pkts,Fwd_Pktl_Len_Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,...,Fwd Act Data Pkts,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
5778,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5287,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
57166,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
29516,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
58609,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45891,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
52416,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
42613,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
43567,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2732,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [16]:
np.where(np.isnan(y_test))

(array([], dtype=int64),)

In [17]:
np.nan_to_num(y_train)

array([0, 0, 1, ..., 1, 1, 0], dtype=int64)

In [18]:
np.nan_to_num(X_train)

array([[8.0000000e+01, 6.0000000e+00, 5.1442550e+06, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [8.0000000e+01, 6.0000000e+00, 9.2250061e+07, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [5.3000000e+01, 1.7000000e+01, 1.5890000e+03, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       ...,
       [3.1280000e+03, 6.0000000e+00, 1.0007740e+06, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [5.3000000e+01, 1.7000000e+01, 1.0160000e+03, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [8.0000000e+01, 6.0000000e+00, 2.1322200e+05, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00]])

In [19]:
df.applymap(np.isreal)

,Dst_Port,Protocol,Flow_Duration,Tot_Fwd_Pkts,Tot_Bwd_Pkts,TotLen_Fwd_Pkts,TotLen_Bwd_Pkts,Fwd_Pktl_Len_Max,Fwd Pkt Len Min,Fwd Pkt Len Mean,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,target_class
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59994,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
59995,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
59996,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
59997,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
59998,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [20]:
# import SVC classifier
from sklearn.svm import SVC


# import metrics to compute accuracy
from sklearn.metrics import accuracy_score


# instantiate classifier with default hyperparameters
svc=SVC() 


# fit classifier to training set
svc.fit(X_train,y_train)


# make predictions on test set
y_pred=svc.predict(X_test)


# compute and print accuracy score
print('Model accuracy score with default hyperparameters: {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').